### ISSUE TITLE
Responsive?

### ISSUE THREAD

**Issue by aayler** [collingo/react-transition-manager#5]
Is it possible to transition to pages that are responsive in dimensions, ie, without set widths and heights as in the examples?

**Comment by collingo** [comment]
Yes responsive pages should not be an issue. It's simply a matter of adapting the CSS to your needs. I've had success using something similar to the following for 100% width responsive pages...

``` css
.translate .page.add {
  transform: translate(100%);
}
.translate .page.show {
  transform: translate(0%);
}
.translate .page.hide {
  transform: translate(-100%);
}
```

Does that cover your use case?
